# Generated by Django 6.0.2 on 2026-03-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_criar_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cuidadores/'),
        ),
    ]
