# Generated by Django 6.0.2 on 2026-08-30 23:58

from django.db import migrations, models


def concluir_agendamento_exemplo(apps, schema_editor):
    Agendamento = apps.get_model('paginas', 'Agendamento')

    Agendamento.objects.filter(
        usuario__username='augusto@email.com',
        cuidador__usuario__username='joao@email.com',
        pet__nome='Rex',
    ).update(status='CONCLUIDO')


def reverter_agendamento_exemplo(apps, schema_editor):
    Agendamento = apps.get_model('paginas', 'Agendamento')

    Agendamento.objects.filter(
        usuario__username='augusto@email.com',
        cuidador__usuario__username='joao@email.com',
        pet__nome='Rex',
    ).update(status='PENDENTE')


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_cuidador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10),
        ),
        migrations.RunPython(
            concluir_agendamento_exemplo,
            reverter_agendamento_exemplo,
        ),
    ]
